baseURL = "https://tcurls.net/"
languageCode = "en-us"
title = "T's Personal Website"
theme = "hermit-v2"

[languages]
  [languages.en]
    title = "T's Personal Website"
    [languages.en.params]
      homeSubtitle = "Check out what I'm up to!"
    weight = 1

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[params.author]
  name = "T Curley"

[params]
  # description = "CHANGE ME SITE DESCRIPTION"
  # images = [""]
  themeColor = "#523473"

  footerCopyright = ' <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  #footerHideThemeName = false
  # bgImg = ""
  gitUrl = "https://github.com/curleyt1/tcurlsnet/tree/main"

  shareSocial = true

  [[params.socialLinks]]
    name = "bluesky"
    url = "https://bsky.app/profile/tcurls.net"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/curleyt1"

  [[params.socialLinks]]
    name = "twitch"
    url = "https://twitch.tv/tkurls"
